# Generated by Django 4.2.7 on 2025-09-12 08:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Language code like N1, N2, etc.', max_length=5, unique=True)),
                ('name', models.CharField(help_text='Language name like English, French, etc.', max_length=50)),
            ],
            options={
                'verbose_name': 'Foreign Language',
                'verbose_name_plural': 'Foreign Languages',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('toan', 'Toán'), ('ngu_van', 'Ngữ Văn'), ('ngoai_ngu', 'Ngoại Ngữ'), ('vat_li', 'Vật Lý'), ('hoa_hoc', 'Hóa Học'), ('sinh_hoc', 'Sinh Học'), ('lich_su', 'Lịch Sử'), ('dia_li', 'Địa Lý'), ('gdcd', 'GDCD')], max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('is_group_a', models.BooleanField(default=False, help_text='True if subject is part of Group A')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='ScoreStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=20)),
                ('level_excellent', models.IntegerField(default=0)),
                ('level_good', models.IntegerField(default=0)),
                ('level_average', models.IntegerField(default=0)),
                ('level_below', models.IntegerField(default=0)),
                ('total_students', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Score Statistics',
                'verbose_name_plural': 'Score Statistics',
                'unique_together': {('subject_name',)},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sbd', models.CharField(help_text='Student registration number (SBD)', max_length=8, unique=True, verbose_name='Registration Number')),
                ('toan', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Toán')),
                ('ngu_van', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Ngữ Văn')),
                ('ngoai_ngu', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Ngoại Ngữ')),
                ('vat_li', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Vật Lý')),
                ('hoa_hoc', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Hóa Học')),
                ('sinh_hoc', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Sinh Học')),
                ('lich_su', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Lịch Sử')),
                ('dia_li', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Địa Lý')),
                ('gdcd', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='GDCD')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ma_ngoai_ngu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scores.foreignlanguage', verbose_name='Foreign Language')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sbd'], name='scores_stud_sbd_eaf324_idx'), models.Index(fields=['toan', 'vat_li', 'hoa_hoc'], name='scores_stud_toan_6e4ba5_idx')],
            },
        ),
    ]
